name: JumpAndRun
version: '${project.version}'
main: ch.ksrminecraft.jumpandrun.JumpAndRun
api-version: '1.21'
load: POSTWORLD
softdepend: ['Multiverse-Core', 'WorldEdit', 'RankPointsAPI']

commands:
  jnr:
    description: Hauptbefehl für Jump and Run (/jnr create|delete|teleport|list|ready|continue|abort|name|unpublish)
    usage: /jnr <create|delete|teleport|list|ready|continue|abort|name|unpublish>
    permission: jumpandrun.use
    aliases: [jumpandrun, jnrp]

permissions:
  jumpandrun.use:
    description: Erlaubt die Nutzung des Hauptbefehls /jnr
    default: true

  jumpandrun.create:
    description: Erlaubt das Erstellen einer JumpAndRun-Welt
    default: op

  jumpandrun.delete:
    description: Erlaubt das Löschen einer JumpAndRun-Welt
    default: op

  jumpandrun.teleport:
    description: Erlaubt das Teleportieren in eine JumpAndRun-Welt
    default: true

  jumpandrun.list:
    description: Erlaubt die Auflistung aller JumpAndRun-Welten
    default: true

  jumpandrun.ready:
    description: Setzt die Welt in den Testmodus, um sie selbst im Survival zu spielen
    default: op

  jumpandrun.continue:
    description: Erlaubt das Fortsetzen einer Draft-Welt
    default: op

  jumpandrun.abort:
    description: Erlaubt das Abbrechen eines Testlaufs (mit Option Welt behalten oder löschen)
    default: op

  jumpandrun.unpublish:
    description: Setzt eine veröffentlichte Welt zurück in den Draft-Modus
    default: op

  jumpandrun.sign.create:
    description: Erlaubt das Erstellen von JumpAndRun-Schildern ([JNR], [JNR-LEADER])
    default: op

  jumpandrun.sign.use:
    description: Erlaubt das Benutzen von JumpAndRun-Schildern
    default: true

  jumpandrun.sign.leader:
    description: Erlaubt das Erstellen und Nutzen von Leader-Schildern
    default: true

  jumpandrun.name:
    description: Erlaubt das Setzen eines Alias-Namens für die JumpAndRun-Welt
    default: op
